### PR TITLE
Overal updates, specifically regarding the using Slurm instead of PBS

### PR DESCRIPTION
**Pull request by moravveji**
This PR contains changes to the main slides (and the .pdf file), docs and the README.
The mojor adaptation is regarding the use of Slurm instead of PBS.
The old training folder is now moved to `/apps/leuven/training/HPC_intro_pbs`, and the `HPC_intro` folder contains Slurm-compatible job scripts (excluding the SAS example).

### CODE REVIEW

**Review by WouterVanAssche — COMMENTED** [review]
The slide that shows how to log in does not yet address MFA, I sent you some slides I once made about mfa, maybe they can be used here again.

**Review by WouterVanAssche — COMMENTED** [review]
On slides 89 and 119 the PBS training project name is still used.
`#SBATCH –-account lp_hpcinfo_training`
Same slide; PowerPoint thought it was being clever and capitalized one of the module commands.
On slide 177, test your self, I guess they should request to join the new group "lp_hpcinfo" now?

**Review by WouterVanAssche — COMMENTED** [review]
On slide 91 and 92:
Aesthetics remark; "STDOUT + STDERR" does not fit in the provided text box.

**Review by WouterVanAssche — COMMENTED** [review]
On slide 93: Is it OK to put a real project name and job id on display here?

**Review by WouterVanAssche — CHANGES_REQUESTED** [review]
On slide 128: Credit pricing is outdated. 
wICE should be included and Thinking kicked out.

**Comment by WouterVanAssche** [comment]
Slides on Worker (primarily 166 & 167) need to be slurmified still.

**Comment by WouterVanAssche** [comment]
Test yourself slide 178 still include hints for pbs commands. A bit more slurmification is needed.

**Comment by moravveji** [comment]
I have pushed my latest changes to this repo, hence this PR is updated. However, all your remarks are not included fully yet.
There are also additional material passed by Wouter which also fit very well in this new format of the slides.
@mselwa : please take it from here. I will also pass the additional slides from Wouter in an email.

**Comment by mselwa** [comment]
File so revised, that pages will not match to make anymore changes. I am closing that one.

**Pull request closed without merging**
